service-1:
  type: mqtt
  brokers: mqtt.vcp-handson.org
  tls: true
  transport: websocket
  username_pw_set:
    username: mqtt
    password: TlQr6657bEWP1zGp
  topics: test-sinetstream-android-20191021
  consistency: AT_LEAST_ONCE
  value_type: text
  retain: true
  # To prevent weird crash, user-specified clientId will be ignored
  # from sinetstream-android(v1.4.5).
  client_id: client-sinetstream-android-20191021-1    # ignored
